[package]
name = "route_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
toml = { workspace = true }
serde_yaml = { workspace = true }
console = { workspace = true }
clap = { version = "4.6.1", features = ["derive"] }

[[bin]]
name = "route_cli"
path = "main.rs"
